### ISSUE TITLE
Installation and `bin/console backup:backup` error

### ISSUE THREAD

**Issue by bcsizmadia** [BlackbitDigitalCommerce/pimcore-backup#9] opened 2022-11-09 16:19 UTC
## Installation error

When executing: `composer require blackbit_digital_commerce/pimcore-backup` I get the following error:

```
Problem 1
    - Root composer.json requires blackbit_digital_commerce/pimcore-backup ^1.2 -> satisfiable by blackbit_digital_commerce/pimcore-backup[v1.2.0, ..., v1.2.8].
    - blackbit_digital_commerce/pimcore-backup[v1.2.0, ..., v1.2.8] require league/flysystem 1.*|2.* -> found league/flysystem[1.0.0-alpha1, ..., 1.x-dev, 2.0.0-alpha.1, ..., 2.x-dev] but the package is fixed to 3.10.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require blackbit_digital_commerce/pimcore-backup:*" to figure out if any version is installable, or "composer require blackbit_digital_commerce/pimcore-backup:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

With the option of `--with-all-dependencies` can be installed or if the https://github.com/BlackbitDigitalCommerce/pimcore-backup/blob/6e78a339c671a436d392bd76f923e3549c853bd6/composer.json#L20 would be `"league/flysystem":"2.*|3.*"`

## `bin/console backup:backup` error

When executing `bin/console backup:backup` I got the following error:

```
Error Output:
================
sed: 1: undefined label 'var/tmp/636bc0702f7836.36087800.sql'
```

If I use `sed -i "" ...` instead of `sed -i ...` in https://github.com/BlackbitDigitalCommerce/pimcore-backup/blob/6e78a339c671a436d392bd76f923e3549c853bd6/Command/BackupCommand.php#L77 the command can make progress, but it fails again at https://github.com/BlackbitDigitalCommerce/pimcore-backup/blob/6e78a339c671a436d392bd76f923e3549c853bd6/Command/BackupCommand.php#L135 with the following error:

```
WARNING [php] Warning: fopen(.../var/tmp/636bbffc7a4623.07478268.tar.gz): Failed to open stream: No such file or directory ["exception" => ErrorException { …}]
Invalid stream provided, expected stream resource, received boolean
```

---

Pimcore version: `^10.5`
Composer version: `2.4.4`
PHP version: `8.0.25`
MariaDB version: `Ver 15.1 Distrib 10.9.3-MariaDB`

**Comment by BlackbitDevs** [comment] 2022-11-11 07:05
Have added support for `league/flysystem` version 3 in just released 1.3.0 (for this dropbox support had to be dropped because there currently is no dropbox adapter for flysystem 3 - have asked for this in https://github.com/spatie/ray/issues/745)

For this `sed` error I currently do not know the cause. It is the first time that I hear of this. Think we have to take a look on your concrete system. Can you write me or help@blackbit.de an email? Then we can check out the whole command which is tried to be executed...

**Comment by BlackbitDevs** [comment] 2022-11-15 16:01
About dropbox support I was wrong. https://github.com/spatie/flysystem-dropbox already supports `league/flysystem` 3 - so I have added dropbox again to support this out of the box.

**Comment by bcsizmadia** [comment] 2022-11-22 16:44
Thanks for your help, if you think this issue can be closed since the installation problem has been solved, the `backup:backup` command has only been tested on a Mac when I opened the issue, but it works on Linux.

**Comment by BlackbitDevs** [comment] 2022-11-22 20:32
Obviously `sed` works differently in MacOS but this is not the main target system of this bundle, so I close this for now. Thx @bcsizmadia anyway for reporting the problem. 
If anyone really needs MacOS support, please add a comment here...

**Closed as completed by BlackbitDevs** 2022-11-22 20:32 UTC
